#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestTyping.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbBestTyping")]
	public partial class DataBestTypingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUSERPROGESS(USERPROGESS instance);
    partial void UpdateUSERPROGESS(USERPROGESS instance);
    partial void DeleteUSERPROGESS(USERPROGESS instance);
    partial void InsertEXERCISE(EXERCISE instance);
    partial void UpdateEXERCISE(EXERCISE instance);
    partial void DeleteEXERCISE(EXERCISE instance);
    partial void InsertEXERCISETEXT(EXERCISETEXT instance);
    partial void UpdateEXERCISETEXT(EXERCISETEXT instance);
    partial void DeleteEXERCISETEXT(EXERCISETEXT instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    partial void InsertEXERCISELANGUAGE(EXERCISELANGUAGE instance);
    partial void UpdateEXERCISELANGUAGE(EXERCISELANGUAGE instance);
    partial void DeleteEXERCISELANGUAGE(EXERCISELANGUAGE instance);
    partial void InsertTYPINGRESULT(TYPINGRESULT instance);
    partial void UpdateTYPINGRESULT(TYPINGRESULT instance);
    partial void DeleteTYPINGRESULT(TYPINGRESULT instance);
    partial void InsertCOMPETITION(COMPETITION instance);
    partial void UpdateCOMPETITION(COMPETITION instance);
    partial void DeleteCOMPETITION(COMPETITION instance);
    partial void InsertTEXTPRACTICE(TEXTPRACTICE instance);
    partial void UpdateTEXTPRACTICE(TEXTPRACTICE instance);
    partial void DeleteTEXTPRACTICE(TEXTPRACTICE instance);
    partial void InsertTYPINGRESULTGAME(TYPINGRESULTGAME instance);
    partial void UpdateTYPINGRESULTGAME(TYPINGRESULTGAME instance);
    partial void DeleteTYPINGRESULTGAME(TYPINGRESULTGAME instance);
    partial void InsertCLASSROOM(CLASSROOM instance);
    partial void UpdateCLASSROOM(CLASSROOM instance);
    partial void DeleteCLASSROOM(CLASSROOM instance);
    partial void InsertTEXTTESTEDU(TEXTTESTEDU instance);
    partial void UpdateTEXTTESTEDU(TEXTTESTEDU instance);
    partial void DeleteTEXTTESTEDU(TEXTTESTEDU instance);
    partial void InsertTESTEDU(TESTEDU instance);
    partial void UpdateTESTEDU(TESTEDU instance);
    partial void DeleteTESTEDU(TESTEDU instance);
    partial void InsertTYPINGRESULTEDU(TYPINGRESULTEDU instance);
    partial void UpdateTYPINGRESULTEDU(TYPINGRESULTEDU instance);
    partial void DeleteTYPINGRESULTEDU(TYPINGRESULTEDU instance);
    #endregion
		
		public DataBestTypingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DbBestTypingConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBestTypingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBestTypingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBestTypingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBestTypingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USERPROGESS> USERPROGESSes
		{
			get
			{
				return this.GetTable<USERPROGESS>();
			}
		}
		
		public System.Data.Linq.Table<EXERCISE> EXERCISEs
		{
			get
			{
				return this.GetTable<EXERCISE>();
			}
		}
		
		public System.Data.Linq.Table<EXERCISETEXT> EXERCISETEXTs
		{
			get
			{
				return this.GetTable<EXERCISETEXT>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		public System.Data.Linq.Table<EXERCISELANGUAGE> EXERCISELANGUAGEs
		{
			get
			{
				return this.GetTable<EXERCISELANGUAGE>();
			}
		}
		
		public System.Data.Linq.Table<TYPINGRESULT> TYPINGRESULTs
		{
			get
			{
				return this.GetTable<TYPINGRESULT>();
			}
		}
		
		public System.Data.Linq.Table<COMPETITION> COMPETITIONs
		{
			get
			{
				return this.GetTable<COMPETITION>();
			}
		}
		
		public System.Data.Linq.Table<TEXTPRACTICE> TEXTPRACTICEs
		{
			get
			{
				return this.GetTable<TEXTPRACTICE>();
			}
		}
		
		public System.Data.Linq.Table<TYPINGRESULTGAME> TYPINGRESULTGAMEs
		{
			get
			{
				return this.GetTable<TYPINGRESULTGAME>();
			}
		}
		
		public System.Data.Linq.Table<CLASSROOM> CLASSROOMs
		{
			get
			{
				return this.GetTable<CLASSROOM>();
			}
		}
		
		public System.Data.Linq.Table<TEXTTESTEDU> TEXTTESTEDUs
		{
			get
			{
				return this.GetTable<TEXTTESTEDU>();
			}
		}
		
		public System.Data.Linq.Table<TESTEDU> TESTEDUs
		{
			get
			{
				return this.GetTable<TESTEDU>();
			}
		}
		
		public System.Data.Linq.Table<TYPINGRESULTEDU> TYPINGRESULTEDUs
		{
			get
			{
				return this.GetTable<TYPINGRESULTEDU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERPROGESS")]
	public partial class USERPROGESS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProgressID;
		
		private int _UserID;
		
		private int _SoTuDaGo;
		
		private int _SoBaiKiemTra;
		
		private int _CuocThiThamGia;
		
		private int _WPMTotNhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProgressIDChanging(int value);
    partial void OnProgressIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnSoTuDaGoChanging(int value);
    partial void OnSoTuDaGoChanged();
    partial void OnSoBaiKiemTraChanging(int value);
    partial void OnSoBaiKiemTraChanged();
    partial void OnCuocThiThamGiaChanging(int value);
    partial void OnCuocThiThamGiaChanged();
    partial void OnWPMTotNhatChanging(int value);
    partial void OnWPMTotNhatChanged();
    #endregion
		
		public USERPROGESS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgressID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProgressID
		{
			get
			{
				return this._ProgressID;
			}
			set
			{
				if ((this._ProgressID != value))
				{
					this.OnProgressIDChanging(value);
					this.SendPropertyChanging();
					this._ProgressID = value;
					this.SendPropertyChanged("ProgressID");
					this.OnProgressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTuDaGo", DbType="Int NOT NULL")]
		public int SoTuDaGo
		{
			get
			{
				return this._SoTuDaGo;
			}
			set
			{
				if ((this._SoTuDaGo != value))
				{
					this.OnSoTuDaGoChanging(value);
					this.SendPropertyChanging();
					this._SoTuDaGo = value;
					this.SendPropertyChanged("SoTuDaGo");
					this.OnSoTuDaGoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBaiKiemTra", DbType="Int NOT NULL")]
		public int SoBaiKiemTra
		{
			get
			{
				return this._SoBaiKiemTra;
			}
			set
			{
				if ((this._SoBaiKiemTra != value))
				{
					this.OnSoBaiKiemTraChanging(value);
					this.SendPropertyChanging();
					this._SoBaiKiemTra = value;
					this.SendPropertyChanged("SoBaiKiemTra");
					this.OnSoBaiKiemTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocThiThamGia", DbType="Int NOT NULL")]
		public int CuocThiThamGia
		{
			get
			{
				return this._CuocThiThamGia;
			}
			set
			{
				if ((this._CuocThiThamGia != value))
				{
					this.OnCuocThiThamGiaChanging(value);
					this.SendPropertyChanging();
					this._CuocThiThamGia = value;
					this.SendPropertyChanged("CuocThiThamGia");
					this.OnCuocThiThamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPMTotNhat", DbType="Int NOT NULL")]
		public int WPMTotNhat
		{
			get
			{
				return this._WPMTotNhat;
			}
			set
			{
				if ((this._WPMTotNhat != value))
				{
					this.OnWPMTotNhatChanging(value);
					this.SendPropertyChanging();
					this._WPMTotNhat = value;
					this.SendPropertyChanged("WPMTotNhat");
					this.OnWPMTotNhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXERCISE")]
	public partial class EXERCISE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExerciseId;
		
		private string _Title;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExerciseIdChanging(int value);
    partial void OnExerciseIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public EXERCISE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExerciseId
		{
			get
			{
				return this._ExerciseId;
			}
			set
			{
				if ((this._ExerciseId != value))
				{
					this.OnExerciseIdChanging(value);
					this.SendPropertyChanging();
					this._ExerciseId = value;
					this.SendPropertyChanged("ExerciseId");
					this.OnExerciseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXERCISETEXT")]
	public partial class EXERCISETEXT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExerciseTextID;
		
		private System.Nullable<int> _ExerciseID;
		
		private string _Text;
		
		private System.Nullable<int> _LanguageID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExerciseTextIDChanging(int value);
    partial void OnExerciseTextIDChanged();
    partial void OnExerciseIDChanging(System.Nullable<int> value);
    partial void OnExerciseIDChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnLanguageIDChanging(System.Nullable<int> value);
    partial void OnLanguageIDChanged();
    #endregion
		
		public EXERCISETEXT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseTextID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExerciseTextID
		{
			get
			{
				return this._ExerciseTextID;
			}
			set
			{
				if ((this._ExerciseTextID != value))
				{
					this.OnExerciseTextIDChanging(value);
					this.SendPropertyChanging();
					this._ExerciseTextID = value;
					this.SendPropertyChanged("ExerciseTextID");
					this.OnExerciseTextIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseID", DbType="Int")]
		public System.Nullable<int> ExerciseID
		{
			get
			{
				return this._ExerciseID;
			}
			set
			{
				if ((this._ExerciseID != value))
				{
					this.OnExerciseIDChanging(value);
					this.SendPropertyChanging();
					this._ExerciseID = value;
					this.SendPropertyChanged("ExerciseID");
					this.OnExerciseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX)")]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int")]
		public System.Nullable<int> LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this.OnLanguageIDChanging(value);
					this.SendPropertyChanging();
					this._LanguageID = value;
					this.SendPropertyChanged("LanguageID");
					this.OnLanguageIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[USER]")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _HoTen;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Email;
		
		private string _Avatar;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _XacMinh;
		
		private string _LinkVerification;
		
		private System.Nullable<bool> _IsEnable;
		
		private string _GioiThieu;
		
		private System.Nullable<long> _CreateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAvatarChanging(string value);
    partial void OnAvatarChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnXacMinhChanging(string value);
    partial void OnXacMinhChanged();
    partial void OnLinkVerificationChanging(string value);
    partial void OnLinkVerificationChanged();
    partial void OnIsEnableChanging(System.Nullable<bool> value);
    partial void OnIsEnableChanged();
    partial void OnGioiThieuChanging(string value);
    partial void OnGioiThieuChanged();
    partial void OnCreateDateChanging(System.Nullable<long> value);
    partial void OnCreateDateChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(255)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XacMinh", DbType="VarChar(6)")]
		public string XacMinh
		{
			get
			{
				return this._XacMinh;
			}
			set
			{
				if ((this._XacMinh != value))
				{
					this.OnXacMinhChanging(value);
					this.SendPropertyChanging();
					this._XacMinh = value;
					this.SendPropertyChanged("XacMinh");
					this.OnXacMinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkVerification", DbType="NVarChar(255)")]
		public string LinkVerification
		{
			get
			{
				return this._LinkVerification;
			}
			set
			{
				if ((this._LinkVerification != value))
				{
					this.OnLinkVerificationChanging(value);
					this.SendPropertyChanging();
					this._LinkVerification = value;
					this.SendPropertyChanged("LinkVerification");
					this.OnLinkVerificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnable", DbType="Bit")]
		public System.Nullable<bool> IsEnable
		{
			get
			{
				return this._IsEnable;
			}
			set
			{
				if ((this._IsEnable != value))
				{
					this.OnIsEnableChanging(value);
					this.SendPropertyChanging();
					this._IsEnable = value;
					this.SendPropertyChanged("IsEnable");
					this.OnIsEnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieu", DbType="NVarChar(MAX)")]
		public string GioiThieu
		{
			get
			{
				return this._GioiThieu;
			}
			set
			{
				if ((this._GioiThieu != value))
				{
					this.OnGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._GioiThieu = value;
					this.SendPropertyChanged("GioiThieu");
					this.OnGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="BigInt")]
		public System.Nullable<long> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXERCISELANGUAGE")]
	public partial class EXERCISELANGUAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LanguageID;
		
		private string _LanguageName;
		
		private string _LanguageAvatar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLanguageIDChanging(int value);
    partial void OnLanguageIDChanged();
    partial void OnLanguageNameChanging(string value);
    partial void OnLanguageNameChanged();
    partial void OnLanguageAvatarChanging(string value);
    partial void OnLanguageAvatarChanged();
    #endregion
		
		public EXERCISELANGUAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this.OnLanguageIDChanging(value);
					this.SendPropertyChanging();
					this._LanguageID = value;
					this.SendPropertyChanged("LanguageID");
					this.OnLanguageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageName", DbType="NVarChar(50)")]
		public string LanguageName
		{
			get
			{
				return this._LanguageName;
			}
			set
			{
				if ((this._LanguageName != value))
				{
					this.OnLanguageNameChanging(value);
					this.SendPropertyChanging();
					this._LanguageName = value;
					this.SendPropertyChanged("LanguageName");
					this.OnLanguageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageAvatar", DbType="NVarChar(255)")]
		public string LanguageAvatar
		{
			get
			{
				return this._LanguageAvatar;
			}
			set
			{
				if ((this._LanguageAvatar != value))
				{
					this.OnLanguageAvatarChanging(value);
					this.SendPropertyChanging();
					this._LanguageAvatar = value;
					this.SendPropertyChanged("LanguageAvatar");
					this.OnLanguageAvatarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TYPINGRESULTS")]
	public partial class TYPINGRESULT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResultId;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<double> _Accuracy;
		
		private System.Nullable<int> _WPM;
		
		private System.Nullable<int> _Mistakes;
		
		private System.Nullable<int> _CorrectWords;
		
		private System.Nullable<int> _TotalWords;
		
		private System.Nullable<long> _Timestamp;
		
		private System.Nullable<int> _ExerciseTextID;
		
		private System.Nullable<int> _KeyStrokes;
		
		private string _JoinCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResultIdChanging(int value);
    partial void OnResultIdChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnAccuracyChanging(System.Nullable<double> value);
    partial void OnAccuracyChanged();
    partial void OnWPMChanging(System.Nullable<int> value);
    partial void OnWPMChanged();
    partial void OnMistakesChanging(System.Nullable<int> value);
    partial void OnMistakesChanged();
    partial void OnCorrectWordsChanging(System.Nullable<int> value);
    partial void OnCorrectWordsChanged();
    partial void OnTotalWordsChanging(System.Nullable<int> value);
    partial void OnTotalWordsChanged();
    partial void OnTimestampChanging(System.Nullable<long> value);
    partial void OnTimestampChanged();
    partial void OnExerciseTextIDChanging(System.Nullable<int> value);
    partial void OnExerciseTextIDChanged();
    partial void OnKeyStrokesChanging(System.Nullable<int> value);
    partial void OnKeyStrokesChanged();
    partial void OnJoinCodeChanging(string value);
    partial void OnJoinCodeChanged();
    #endregion
		
		public TYPINGRESULT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResultId
		{
			get
			{
				return this._ResultId;
			}
			set
			{
				if ((this._ResultId != value))
				{
					this.OnResultIdChanging(value);
					this.SendPropertyChanging();
					this._ResultId = value;
					this.SendPropertyChanged("ResultId");
					this.OnResultIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accuracy", DbType="Float")]
		public System.Nullable<double> Accuracy
		{
			get
			{
				return this._Accuracy;
			}
			set
			{
				if ((this._Accuracy != value))
				{
					this.OnAccuracyChanging(value);
					this.SendPropertyChanging();
					this._Accuracy = value;
					this.SendPropertyChanged("Accuracy");
					this.OnAccuracyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPM", DbType="Int")]
		public System.Nullable<int> WPM
		{
			get
			{
				return this._WPM;
			}
			set
			{
				if ((this._WPM != value))
				{
					this.OnWPMChanging(value);
					this.SendPropertyChanging();
					this._WPM = value;
					this.SendPropertyChanged("WPM");
					this.OnWPMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mistakes", DbType="Int")]
		public System.Nullable<int> Mistakes
		{
			get
			{
				return this._Mistakes;
			}
			set
			{
				if ((this._Mistakes != value))
				{
					this.OnMistakesChanging(value);
					this.SendPropertyChanging();
					this._Mistakes = value;
					this.SendPropertyChanged("Mistakes");
					this.OnMistakesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrectWords", DbType="Int")]
		public System.Nullable<int> CorrectWords
		{
			get
			{
				return this._CorrectWords;
			}
			set
			{
				if ((this._CorrectWords != value))
				{
					this.OnCorrectWordsChanging(value);
					this.SendPropertyChanging();
					this._CorrectWords = value;
					this.SendPropertyChanged("CorrectWords");
					this.OnCorrectWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalWords", DbType="Int")]
		public System.Nullable<int> TotalWords
		{
			get
			{
				return this._TotalWords;
			}
			set
			{
				if ((this._TotalWords != value))
				{
					this.OnTotalWordsChanging(value);
					this.SendPropertyChanging();
					this._TotalWords = value;
					this.SendPropertyChanged("TotalWords");
					this.OnTotalWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="BigInt")]
		public System.Nullable<long> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseTextID", DbType="Int")]
		public System.Nullable<int> ExerciseTextID
		{
			get
			{
				return this._ExerciseTextID;
			}
			set
			{
				if ((this._ExerciseTextID != value))
				{
					this.OnExerciseTextIDChanging(value);
					this.SendPropertyChanging();
					this._ExerciseTextID = value;
					this.SendPropertyChanged("ExerciseTextID");
					this.OnExerciseTextIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyStrokes", DbType="Int")]
		public System.Nullable<int> KeyStrokes
		{
			get
			{
				return this._KeyStrokes;
			}
			set
			{
				if ((this._KeyStrokes != value))
				{
					this.OnKeyStrokesChanging(value);
					this.SendPropertyChanging();
					this._KeyStrokes = value;
					this.SendPropertyChanged("KeyStrokes");
					this.OnKeyStrokesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinCode", DbType="VarChar(25)")]
		public string JoinCode
		{
			get
			{
				return this._JoinCode;
			}
			set
			{
				if ((this._JoinCode != value))
				{
					this.OnJoinCodeChanging(value);
					this.SendPropertyChanging();
					this._JoinCode = value;
					this.SendPropertyChanged("JoinCode");
					this.OnJoinCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMPETITION")]
	public partial class COMPETITION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CompetitionId;
		
		private System.Nullable<int> _PeopleJoin;
		
		private System.Nullable<int> _NumberOfTestsPerformed;
		
		private System.Nullable<long> _CreateDate;
		
		private string _JoinCode;
		
		private System.Nullable<int> _LanguageId;
		
		private System.Nullable<int> _ExerciseTextID;
		
		private System.Nullable<bool> _IsPrivate;
		
		private System.Nullable<int> _UserCreate;
		
		private System.Nullable<bool> _isOpen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompetitionIdChanging(int value);
    partial void OnCompetitionIdChanged();
    partial void OnPeopleJoinChanging(System.Nullable<int> value);
    partial void OnPeopleJoinChanged();
    partial void OnNumberOfTestsPerformedChanging(System.Nullable<int> value);
    partial void OnNumberOfTestsPerformedChanged();
    partial void OnCreateDateChanging(System.Nullable<long> value);
    partial void OnCreateDateChanged();
    partial void OnJoinCodeChanging(string value);
    partial void OnJoinCodeChanged();
    partial void OnLanguageIdChanging(System.Nullable<int> value);
    partial void OnLanguageIdChanged();
    partial void OnExerciseTextIDChanging(System.Nullable<int> value);
    partial void OnExerciseTextIDChanged();
    partial void OnIsPrivateChanging(System.Nullable<bool> value);
    partial void OnIsPrivateChanged();
    partial void OnUserCreateChanging(System.Nullable<int> value);
    partial void OnUserCreateChanged();
    partial void OnisOpenChanging(System.Nullable<bool> value);
    partial void OnisOpenChanged();
    #endregion
		
		public COMPETITION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CompetitionId
		{
			get
			{
				return this._CompetitionId;
			}
			set
			{
				if ((this._CompetitionId != value))
				{
					this.OnCompetitionIdChanging(value);
					this.SendPropertyChanging();
					this._CompetitionId = value;
					this.SendPropertyChanged("CompetitionId");
					this.OnCompetitionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeopleJoin", DbType="Int")]
		public System.Nullable<int> PeopleJoin
		{
			get
			{
				return this._PeopleJoin;
			}
			set
			{
				if ((this._PeopleJoin != value))
				{
					this.OnPeopleJoinChanging(value);
					this.SendPropertyChanging();
					this._PeopleJoin = value;
					this.SendPropertyChanged("PeopleJoin");
					this.OnPeopleJoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfTestsPerformed", DbType="Int")]
		public System.Nullable<int> NumberOfTestsPerformed
		{
			get
			{
				return this._NumberOfTestsPerformed;
			}
			set
			{
				if ((this._NumberOfTestsPerformed != value))
				{
					this.OnNumberOfTestsPerformedChanging(value);
					this.SendPropertyChanging();
					this._NumberOfTestsPerformed = value;
					this.SendPropertyChanged("NumberOfTestsPerformed");
					this.OnNumberOfTestsPerformedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="BigInt")]
		public System.Nullable<long> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinCode", DbType="VarChar(25)")]
		public string JoinCode
		{
			get
			{
				return this._JoinCode;
			}
			set
			{
				if ((this._JoinCode != value))
				{
					this.OnJoinCodeChanging(value);
					this.SendPropertyChanging();
					this._JoinCode = value;
					this.SendPropertyChanged("JoinCode");
					this.OnJoinCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", DbType="Int")]
		public System.Nullable<int> LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					this.OnLanguageIdChanging(value);
					this.SendPropertyChanging();
					this._LanguageId = value;
					this.SendPropertyChanged("LanguageId");
					this.OnLanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseTextID", DbType="Int")]
		public System.Nullable<int> ExerciseTextID
		{
			get
			{
				return this._ExerciseTextID;
			}
			set
			{
				if ((this._ExerciseTextID != value))
				{
					this.OnExerciseTextIDChanging(value);
					this.SendPropertyChanging();
					this._ExerciseTextID = value;
					this.SendPropertyChanged("ExerciseTextID");
					this.OnExerciseTextIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrivate", DbType="Bit")]
		public System.Nullable<bool> IsPrivate
		{
			get
			{
				return this._IsPrivate;
			}
			set
			{
				if ((this._IsPrivate != value))
				{
					this.OnIsPrivateChanging(value);
					this.SendPropertyChanging();
					this._IsPrivate = value;
					this.SendPropertyChanged("IsPrivate");
					this.OnIsPrivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreate", DbType="Int")]
		public System.Nullable<int> UserCreate
		{
			get
			{
				return this._UserCreate;
			}
			set
			{
				if ((this._UserCreate != value))
				{
					this.OnUserCreateChanging(value);
					this.SendPropertyChanging();
					this._UserCreate = value;
					this.SendPropertyChanged("UserCreate");
					this.OnUserCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isOpen", DbType="Bit")]
		public System.Nullable<bool> isOpen
		{
			get
			{
				return this._isOpen;
			}
			set
			{
				if ((this._isOpen != value))
				{
					this.OnisOpenChanging(value);
					this.SendPropertyChanging();
					this._isOpen = value;
					this.SendPropertyChanged("isOpen");
					this.OnisOpenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEXTPRACTICE")]
	public partial class TEXTPRACTICE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _UserCreate;
		
		private string _Text;
		
		private string _Title;
		
		private System.Nullable<int> _TextLength;
		
		private System.Nullable<int> _PeopleIsCompleted;
		
		private System.Nullable<long> _CreatedAt;
		
		private System.Nullable<int> _LanguageID;
		
		private string _JoinCode;
		
		private System.Nullable<bool> _IsPrivate;
		
		private System.Nullable<double> _Rating;
		
		private string _ListUserLike;
		
		private string _ListUserRating;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserCreateChanging(System.Nullable<int> value);
    partial void OnUserCreateChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTextLengthChanging(System.Nullable<int> value);
    partial void OnTextLengthChanged();
    partial void OnPeopleIsCompletedChanging(System.Nullable<int> value);
    partial void OnPeopleIsCompletedChanged();
    partial void OnCreatedAtChanging(System.Nullable<long> value);
    partial void OnCreatedAtChanged();
    partial void OnLanguageIDChanging(System.Nullable<int> value);
    partial void OnLanguageIDChanged();
    partial void OnJoinCodeChanging(string value);
    partial void OnJoinCodeChanged();
    partial void OnIsPrivateChanging(System.Nullable<bool> value);
    partial void OnIsPrivateChanged();
    partial void OnRatingChanging(System.Nullable<double> value);
    partial void OnRatingChanged();
    partial void OnListUserLikeChanging(string value);
    partial void OnListUserLikeChanged();
    partial void OnListUserRatingChanging(string value);
    partial void OnListUserRatingChanged();
    #endregion
		
		public TEXTPRACTICE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreate", DbType="Int")]
		public System.Nullable<int> UserCreate
		{
			get
			{
				return this._UserCreate;
			}
			set
			{
				if ((this._UserCreate != value))
				{
					this.OnUserCreateChanging(value);
					this.SendPropertyChanging();
					this._UserCreate = value;
					this.SendPropertyChanged("UserCreate");
					this.OnUserCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX)")]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLength", DbType="Int")]
		public System.Nullable<int> TextLength
		{
			get
			{
				return this._TextLength;
			}
			set
			{
				if ((this._TextLength != value))
				{
					this.OnTextLengthChanging(value);
					this.SendPropertyChanging();
					this._TextLength = value;
					this.SendPropertyChanged("TextLength");
					this.OnTextLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeopleIsCompleted", DbType="Int")]
		public System.Nullable<int> PeopleIsCompleted
		{
			get
			{
				return this._PeopleIsCompleted;
			}
			set
			{
				if ((this._PeopleIsCompleted != value))
				{
					this.OnPeopleIsCompletedChanging(value);
					this.SendPropertyChanging();
					this._PeopleIsCompleted = value;
					this.SendPropertyChanged("PeopleIsCompleted");
					this.OnPeopleIsCompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="BigInt")]
		public System.Nullable<long> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int")]
		public System.Nullable<int> LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this.OnLanguageIDChanging(value);
					this.SendPropertyChanging();
					this._LanguageID = value;
					this.SendPropertyChanged("LanguageID");
					this.OnLanguageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinCode", DbType="VarChar(25)")]
		public string JoinCode
		{
			get
			{
				return this._JoinCode;
			}
			set
			{
				if ((this._JoinCode != value))
				{
					this.OnJoinCodeChanging(value);
					this.SendPropertyChanging();
					this._JoinCode = value;
					this.SendPropertyChanged("JoinCode");
					this.OnJoinCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrivate", DbType="Bit")]
		public System.Nullable<bool> IsPrivate
		{
			get
			{
				return this._IsPrivate;
			}
			set
			{
				if ((this._IsPrivate != value))
				{
					this.OnIsPrivateChanging(value);
					this.SendPropertyChanging();
					this._IsPrivate = value;
					this.SendPropertyChanged("IsPrivate");
					this.OnIsPrivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Float")]
		public System.Nullable<double> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListUserLike", DbType="NVarChar(MAX)")]
		public string ListUserLike
		{
			get
			{
				return this._ListUserLike;
			}
			set
			{
				if ((this._ListUserLike != value))
				{
					this.OnListUserLikeChanging(value);
					this.SendPropertyChanging();
					this._ListUserLike = value;
					this.SendPropertyChanged("ListUserLike");
					this.OnListUserLikeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListUserRating", DbType="NVarChar(MAX)")]
		public string ListUserRating
		{
			get
			{
				return this._ListUserRating;
			}
			set
			{
				if ((this._ListUserRating != value))
				{
					this.OnListUserRatingChanging(value);
					this.SendPropertyChanging();
					this._ListUserRating = value;
					this.SendPropertyChanged("ListUserRating");
					this.OnListUserRatingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TYPINGRESULTGAME")]
	public partial class TYPINGRESULTGAME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResultId;
		
		private System.Nullable<int> _ExerciseId;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<int> _Score;
		
		private System.Nullable<int> _Score2;
		
		private System.Nullable<long> _Timestamp;
		
		private System.Nullable<int> _Score3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResultIdChanging(int value);
    partial void OnResultIdChanged();
    partial void OnExerciseIdChanging(System.Nullable<int> value);
    partial void OnExerciseIdChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnScoreChanging(System.Nullable<int> value);
    partial void OnScoreChanged();
    partial void OnScore2Changing(System.Nullable<int> value);
    partial void OnScore2Changed();
    partial void OnTimestampChanging(System.Nullable<long> value);
    partial void OnTimestampChanged();
    partial void OnScore3Changing(System.Nullable<int> value);
    partial void OnScore3Changed();
    #endregion
		
		public TYPINGRESULTGAME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResultId
		{
			get
			{
				return this._ResultId;
			}
			set
			{
				if ((this._ResultId != value))
				{
					this.OnResultIdChanging(value);
					this.SendPropertyChanging();
					this._ResultId = value;
					this.SendPropertyChanged("ResultId");
					this.OnResultIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseId", DbType="Int")]
		public System.Nullable<int> ExerciseId
		{
			get
			{
				return this._ExerciseId;
			}
			set
			{
				if ((this._ExerciseId != value))
				{
					this.OnExerciseIdChanging(value);
					this.SendPropertyChanging();
					this._ExerciseId = value;
					this.SendPropertyChanged("ExerciseId");
					this.OnExerciseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Int")]
		public System.Nullable<int> Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score2", DbType="Int")]
		public System.Nullable<int> Score2
		{
			get
			{
				return this._Score2;
			}
			set
			{
				if ((this._Score2 != value))
				{
					this.OnScore2Changing(value);
					this.SendPropertyChanging();
					this._Score2 = value;
					this.SendPropertyChanged("Score2");
					this.OnScore2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="BigInt")]
		public System.Nullable<long> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score3", DbType="Int")]
		public System.Nullable<int> Score3
		{
			get
			{
				return this._Score3;
			}
			set
			{
				if ((this._Score3 != value))
				{
					this.OnScore3Changing(value);
					this.SendPropertyChanging();
					this._Score3 = value;
					this.SendPropertyChanged("Score3");
					this.OnScore3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASSROOM")]
	public partial class CLASSROOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClassRoomId;
		
		private string _AvatarClassRoom;
		
		private string _ClassName;
		
		private string _Description;
		
		private System.Nullable<bool> _IsPrivate;
		
		private System.Nullable<int> _UserCreate;
		
		private string _JoinCode;
		
		private string _PassClassRoom;
		
		private string _ListUserJoin;
		
		private System.Nullable<long> _CreateDate;
		
		private string _ListUserRequest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClassRoomIdChanging(int value);
    partial void OnClassRoomIdChanged();
    partial void OnAvatarClassRoomChanging(string value);
    partial void OnAvatarClassRoomChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsPrivateChanging(System.Nullable<bool> value);
    partial void OnIsPrivateChanged();
    partial void OnUserCreateChanging(System.Nullable<int> value);
    partial void OnUserCreateChanged();
    partial void OnJoinCodeChanging(string value);
    partial void OnJoinCodeChanged();
    partial void OnPassClassRoomChanging(string value);
    partial void OnPassClassRoomChanged();
    partial void OnListUserJoinChanging(string value);
    partial void OnListUserJoinChanged();
    partial void OnCreateDateChanging(System.Nullable<long> value);
    partial void OnCreateDateChanged();
    partial void OnListUserRequestChanging(string value);
    partial void OnListUserRequestChanged();
    #endregion
		
		public CLASSROOM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassRoomId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClassRoomId
		{
			get
			{
				return this._ClassRoomId;
			}
			set
			{
				if ((this._ClassRoomId != value))
				{
					this.OnClassRoomIdChanging(value);
					this.SendPropertyChanging();
					this._ClassRoomId = value;
					this.SendPropertyChanged("ClassRoomId");
					this.OnClassRoomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvatarClassRoom", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string AvatarClassRoom
		{
			get
			{
				return this._AvatarClassRoom;
			}
			set
			{
				if ((this._AvatarClassRoom != value))
				{
					this.OnAvatarClassRoomChanging(value);
					this.SendPropertyChanging();
					this._AvatarClassRoom = value;
					this.SendPropertyChanged("AvatarClassRoom");
					this.OnAvatarClassRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(255)")]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrivate", DbType="Bit")]
		public System.Nullable<bool> IsPrivate
		{
			get
			{
				return this._IsPrivate;
			}
			set
			{
				if ((this._IsPrivate != value))
				{
					this.OnIsPrivateChanging(value);
					this.SendPropertyChanging();
					this._IsPrivate = value;
					this.SendPropertyChanged("IsPrivate");
					this.OnIsPrivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreate", DbType="Int")]
		public System.Nullable<int> UserCreate
		{
			get
			{
				return this._UserCreate;
			}
			set
			{
				if ((this._UserCreate != value))
				{
					this.OnUserCreateChanging(value);
					this.SendPropertyChanging();
					this._UserCreate = value;
					this.SendPropertyChanged("UserCreate");
					this.OnUserCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinCode", DbType="VarChar(25)")]
		public string JoinCode
		{
			get
			{
				return this._JoinCode;
			}
			set
			{
				if ((this._JoinCode != value))
				{
					this.OnJoinCodeChanging(value);
					this.SendPropertyChanging();
					this._JoinCode = value;
					this.SendPropertyChanged("JoinCode");
					this.OnJoinCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassClassRoom", DbType="VarChar(25)")]
		public string PassClassRoom
		{
			get
			{
				return this._PassClassRoom;
			}
			set
			{
				if ((this._PassClassRoom != value))
				{
					this.OnPassClassRoomChanging(value);
					this.SendPropertyChanging();
					this._PassClassRoom = value;
					this.SendPropertyChanged("PassClassRoom");
					this.OnPassClassRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListUserJoin", DbType="NVarChar(MAX)")]
		public string ListUserJoin
		{
			get
			{
				return this._ListUserJoin;
			}
			set
			{
				if ((this._ListUserJoin != value))
				{
					this.OnListUserJoinChanging(value);
					this.SendPropertyChanging();
					this._ListUserJoin = value;
					this.SendPropertyChanged("ListUserJoin");
					this.OnListUserJoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="BigInt")]
		public System.Nullable<long> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListUserRequest", DbType="NVarChar(MAX)")]
		public string ListUserRequest
		{
			get
			{
				return this._ListUserRequest;
			}
			set
			{
				if ((this._ListUserRequest != value))
				{
					this.OnListUserRequestChanging(value);
					this.SendPropertyChanging();
					this._ListUserRequest = value;
					this.SendPropertyChanged("ListUserRequest");
					this.OnListUserRequestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEXTTESTEDU")]
	public partial class TEXTTESTEDU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _UserCreate;
		
		private string _Text;
		
		private string _Title;
		
		private System.Nullable<long> _CreateDate;
		
		private System.Nullable<int> _LanguageID;
		
		private System.Nullable<bool> _IsPrivate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserCreateChanging(System.Nullable<int> value);
    partial void OnUserCreateChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnCreateDateChanging(System.Nullable<long> value);
    partial void OnCreateDateChanged();
    partial void OnLanguageIDChanging(System.Nullable<int> value);
    partial void OnLanguageIDChanged();
    partial void OnIsPrivateChanging(System.Nullable<bool> value);
    partial void OnIsPrivateChanged();
    #endregion
		
		public TEXTTESTEDU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreate", DbType="Int")]
		public System.Nullable<int> UserCreate
		{
			get
			{
				return this._UserCreate;
			}
			set
			{
				if ((this._UserCreate != value))
				{
					this.OnUserCreateChanging(value);
					this.SendPropertyChanging();
					this._UserCreate = value;
					this.SendPropertyChanged("UserCreate");
					this.OnUserCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX)")]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="BigInt")]
		public System.Nullable<long> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int")]
		public System.Nullable<int> LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this.OnLanguageIDChanging(value);
					this.SendPropertyChanging();
					this._LanguageID = value;
					this.SendPropertyChanged("LanguageID");
					this.OnLanguageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrivate", DbType="Bit")]
		public System.Nullable<bool> IsPrivate
		{
			get
			{
				return this._IsPrivate;
			}
			set
			{
				if ((this._IsPrivate != value))
				{
					this.OnIsPrivateChanging(value);
					this.SendPropertyChanging();
					this._IsPrivate = value;
					this.SendPropertyChanged("IsPrivate");
					this.OnIsPrivateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TESTEDU")]
	public partial class TESTEDU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _UserCreate;
		
		private string _TitleTest;
		
		private System.Nullable<int> _TextID;
		
		private System.Nullable<bool> _IsRandom;
		
		private string _ListClass;
		
		private System.Nullable<long> _DateStart;
		
		private System.Nullable<long> _DateEnd;
		
		private System.Nullable<int> _ExamDuration;
		
		private string _CodeLink;
		
		private string _PassTest;
		
		private System.Nullable<int> _MaxAttempts;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<long> _CreateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserCreateChanging(System.Nullable<int> value);
    partial void OnUserCreateChanged();
    partial void OnTitleTestChanging(string value);
    partial void OnTitleTestChanged();
    partial void OnTextIDChanging(System.Nullable<int> value);
    partial void OnTextIDChanged();
    partial void OnIsRandomChanging(System.Nullable<bool> value);
    partial void OnIsRandomChanged();
    partial void OnListClassChanging(string value);
    partial void OnListClassChanged();
    partial void OnDateStartChanging(System.Nullable<long> value);
    partial void OnDateStartChanged();
    partial void OnDateEndChanging(System.Nullable<long> value);
    partial void OnDateEndChanged();
    partial void OnExamDurationChanging(System.Nullable<int> value);
    partial void OnExamDurationChanged();
    partial void OnCodeLinkChanging(string value);
    partial void OnCodeLinkChanged();
    partial void OnPassTestChanging(string value);
    partial void OnPassTestChanged();
    partial void OnMaxAttemptsChanging(System.Nullable<int> value);
    partial void OnMaxAttemptsChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnCreateDateChanging(System.Nullable<long> value);
    partial void OnCreateDateChanged();
    #endregion
		
		public TESTEDU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreate", DbType="Int")]
		public System.Nullable<int> UserCreate
		{
			get
			{
				return this._UserCreate;
			}
			set
			{
				if ((this._UserCreate != value))
				{
					this.OnUserCreateChanging(value);
					this.SendPropertyChanging();
					this._UserCreate = value;
					this.SendPropertyChanged("UserCreate");
					this.OnUserCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleTest", DbType="NVarChar(MAX)")]
		public string TitleTest
		{
			get
			{
				return this._TitleTest;
			}
			set
			{
				if ((this._TitleTest != value))
				{
					this.OnTitleTestChanging(value);
					this.SendPropertyChanging();
					this._TitleTest = value;
					this.SendPropertyChanged("TitleTest");
					this.OnTitleTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextID", DbType="Int")]
		public System.Nullable<int> TextID
		{
			get
			{
				return this._TextID;
			}
			set
			{
				if ((this._TextID != value))
				{
					this.OnTextIDChanging(value);
					this.SendPropertyChanging();
					this._TextID = value;
					this.SendPropertyChanged("TextID");
					this.OnTextIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRandom", DbType="Bit")]
		public System.Nullable<bool> IsRandom
		{
			get
			{
				return this._IsRandom;
			}
			set
			{
				if ((this._IsRandom != value))
				{
					this.OnIsRandomChanging(value);
					this.SendPropertyChanging();
					this._IsRandom = value;
					this.SendPropertyChanged("IsRandom");
					this.OnIsRandomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListClass", DbType="NVarChar(MAX)")]
		public string ListClass
		{
			get
			{
				return this._ListClass;
			}
			set
			{
				if ((this._ListClass != value))
				{
					this.OnListClassChanging(value);
					this.SendPropertyChanging();
					this._ListClass = value;
					this.SendPropertyChanged("ListClass");
					this.OnListClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStart", DbType="BigInt")]
		public System.Nullable<long> DateStart
		{
			get
			{
				return this._DateStart;
			}
			set
			{
				if ((this._DateStart != value))
				{
					this.OnDateStartChanging(value);
					this.SendPropertyChanging();
					this._DateStart = value;
					this.SendPropertyChanged("DateStart");
					this.OnDateStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEnd", DbType="BigInt")]
		public System.Nullable<long> DateEnd
		{
			get
			{
				return this._DateEnd;
			}
			set
			{
				if ((this._DateEnd != value))
				{
					this.OnDateEndChanging(value);
					this.SendPropertyChanging();
					this._DateEnd = value;
					this.SendPropertyChanged("DateEnd");
					this.OnDateEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamDuration", DbType="Int")]
		public System.Nullable<int> ExamDuration
		{
			get
			{
				return this._ExamDuration;
			}
			set
			{
				if ((this._ExamDuration != value))
				{
					this.OnExamDurationChanging(value);
					this.SendPropertyChanging();
					this._ExamDuration = value;
					this.SendPropertyChanged("ExamDuration");
					this.OnExamDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeLink", DbType="VarChar(25)")]
		public string CodeLink
		{
			get
			{
				return this._CodeLink;
			}
			set
			{
				if ((this._CodeLink != value))
				{
					this.OnCodeLinkChanging(value);
					this.SendPropertyChanging();
					this._CodeLink = value;
					this.SendPropertyChanged("CodeLink");
					this.OnCodeLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassTest", DbType="VarChar(25)")]
		public string PassTest
		{
			get
			{
				return this._PassTest;
			}
			set
			{
				if ((this._PassTest != value))
				{
					this.OnPassTestChanging(value);
					this.SendPropertyChanging();
					this._PassTest = value;
					this.SendPropertyChanged("PassTest");
					this.OnPassTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAttempts", DbType="Int")]
		public System.Nullable<int> MaxAttempts
		{
			get
			{
				return this._MaxAttempts;
			}
			set
			{
				if ((this._MaxAttempts != value))
				{
					this.OnMaxAttemptsChanging(value);
					this.SendPropertyChanging();
					this._MaxAttempts = value;
					this.SendPropertyChanged("MaxAttempts");
					this.OnMaxAttemptsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="BigInt")]
		public System.Nullable<long> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TYPINGRESULTEDU")]
	public partial class TYPINGRESULTEDU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResultId;
		
		private System.Nullable<int> _TestId;
		
		private System.Nullable<int> _ClassRoomId;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<double> _Accuracy;
		
		private System.Nullable<int> _WPM;
		
		private System.Nullable<int> _Mistakes;
		
		private System.Nullable<int> _CorrectWords;
		
		private System.Nullable<int> _KeyStrokes;
		
		private System.Nullable<long> _Timestamp;
		
		private System.Nullable<int> _WrongCharacter;
		
		private System.Nullable<int> _CorrectCharacter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResultIdChanging(int value);
    partial void OnResultIdChanged();
    partial void OnTestIdChanging(System.Nullable<int> value);
    partial void OnTestIdChanged();
    partial void OnClassRoomIdChanging(System.Nullable<int> value);
    partial void OnClassRoomIdChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnAccuracyChanging(System.Nullable<double> value);
    partial void OnAccuracyChanged();
    partial void OnWPMChanging(System.Nullable<int> value);
    partial void OnWPMChanged();
    partial void OnMistakesChanging(System.Nullable<int> value);
    partial void OnMistakesChanged();
    partial void OnCorrectWordsChanging(System.Nullable<int> value);
    partial void OnCorrectWordsChanged();
    partial void OnKeyStrokesChanging(System.Nullable<int> value);
    partial void OnKeyStrokesChanged();
    partial void OnTimestampChanging(System.Nullable<long> value);
    partial void OnTimestampChanged();
    partial void OnWrongCharacterChanging(System.Nullable<int> value);
    partial void OnWrongCharacterChanged();
    partial void OnCorrectCharacterChanging(System.Nullable<int> value);
    partial void OnCorrectCharacterChanged();
    #endregion
		
		public TYPINGRESULTEDU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResultId
		{
			get
			{
				return this._ResultId;
			}
			set
			{
				if ((this._ResultId != value))
				{
					this.OnResultIdChanging(value);
					this.SendPropertyChanging();
					this._ResultId = value;
					this.SendPropertyChanged("ResultId");
					this.OnResultIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestId", DbType="Int")]
		public System.Nullable<int> TestId
		{
			get
			{
				return this._TestId;
			}
			set
			{
				if ((this._TestId != value))
				{
					this.OnTestIdChanging(value);
					this.SendPropertyChanging();
					this._TestId = value;
					this.SendPropertyChanged("TestId");
					this.OnTestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassRoomId", DbType="Int")]
		public System.Nullable<int> ClassRoomId
		{
			get
			{
				return this._ClassRoomId;
			}
			set
			{
				if ((this._ClassRoomId != value))
				{
					this.OnClassRoomIdChanging(value);
					this.SendPropertyChanging();
					this._ClassRoomId = value;
					this.SendPropertyChanged("ClassRoomId");
					this.OnClassRoomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accuracy", DbType="Float")]
		public System.Nullable<double> Accuracy
		{
			get
			{
				return this._Accuracy;
			}
			set
			{
				if ((this._Accuracy != value))
				{
					this.OnAccuracyChanging(value);
					this.SendPropertyChanging();
					this._Accuracy = value;
					this.SendPropertyChanged("Accuracy");
					this.OnAccuracyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WPM", DbType="Int")]
		public System.Nullable<int> WPM
		{
			get
			{
				return this._WPM;
			}
			set
			{
				if ((this._WPM != value))
				{
					this.OnWPMChanging(value);
					this.SendPropertyChanging();
					this._WPM = value;
					this.SendPropertyChanged("WPM");
					this.OnWPMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mistakes", DbType="Int")]
		public System.Nullable<int> Mistakes
		{
			get
			{
				return this._Mistakes;
			}
			set
			{
				if ((this._Mistakes != value))
				{
					this.OnMistakesChanging(value);
					this.SendPropertyChanging();
					this._Mistakes = value;
					this.SendPropertyChanged("Mistakes");
					this.OnMistakesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrectWords", DbType="Int")]
		public System.Nullable<int> CorrectWords
		{
			get
			{
				return this._CorrectWords;
			}
			set
			{
				if ((this._CorrectWords != value))
				{
					this.OnCorrectWordsChanging(value);
					this.SendPropertyChanging();
					this._CorrectWords = value;
					this.SendPropertyChanged("CorrectWords");
					this.OnCorrectWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyStrokes", DbType="Int")]
		public System.Nullable<int> KeyStrokes
		{
			get
			{
				return this._KeyStrokes;
			}
			set
			{
				if ((this._KeyStrokes != value))
				{
					this.OnKeyStrokesChanging(value);
					this.SendPropertyChanging();
					this._KeyStrokes = value;
					this.SendPropertyChanged("KeyStrokes");
					this.OnKeyStrokesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="BigInt")]
		public System.Nullable<long> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WrongCharacter", DbType="Int")]
		public System.Nullable<int> WrongCharacter
		{
			get
			{
				return this._WrongCharacter;
			}
			set
			{
				if ((this._WrongCharacter != value))
				{
					this.OnWrongCharacterChanging(value);
					this.SendPropertyChanging();
					this._WrongCharacter = value;
					this.SendPropertyChanged("WrongCharacter");
					this.OnWrongCharacterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrectCharacter", DbType="Int")]
		public System.Nullable<int> CorrectCharacter
		{
			get
			{
				return this._CorrectCharacter;
			}
			set
			{
				if ((this._CorrectCharacter != value))
				{
					this.OnCorrectCharacterChanging(value);
					this.SendPropertyChanging();
					this._CorrectCharacter = value;
					this.SendPropertyChanged("CorrectCharacter");
					this.OnCorrectCharacterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
